### ISSUE TITLE
numbers in the banner

### ISSUE THREAD

**Issue by gavalian** [vivekverma007/BannerBash#1]
Very nice script. Would it be possible to add numbers and ". + - ! " symbols ?

**Comment by virtualvivek** [comment]
> Very nice script. Would it be possible to add numbers and ". + - ! " symbols ?

Hi @gavalian 

i have updated the library and now it comes with 
 - alphabets
 - numbers
 - math symbols
 - special characters

you can try for the new update and check if it fulfills your purpose 
you can add issue for more characters too!
