### ISSUE TITLE
alphabet shade not correct

### ISSUE THREAD

**Issue by Austinsuyoyo** [vivekverma007/BannerBash#2]
When type "yo", the shade of "o"' is not correct
![image](https://user-images.githubusercontent.com/15572804/92991344-d67f3280-f515-11ea-977c-cafcb6d7f761.png)

**Comment by virtualvivek** [comment]
> When type "yo", the shade of "o"' is not correct
> ![image](https://user-images.githubusercontent.com/15572804/92991344-d67f3280-f515-11ea-977c-cafcb6d7f761.png)

Hi @Austinsuyoyo 

I have updated the library today and finally resolved the uneven shadow in letter ```"O"``` 
as from the above snapshot ,
### What was wrong:
Actually the extra spacing of letter ```"Y"``` is creating space shift for another adjacent letters and now has been resolved.
😄

### Now you can try the latest version ```-v1.2```
