### ISSUE TITLE
banner running for shell

### ISSUE THREAD

**Issue by gavalian** [vivekverma007/BannerBash#3]
Hi,
Thanks for implementing the numbers and symbols.
I had problems running your script in SHELL (some docker small linux
distributions do not come with BASH). I have made some modificaitions
to loops, which allows it to run in both BASH and SHELL.

If you want to modify the code : here is my version:

https://github.com/gavalian/language-benchmarks/blob/master/scripts/monitorBanner.sh

**Comment by virtualvivek** [comment]
> Hi,
> Thanks for implementing the numbers and symbols.
> I had problems running your script in SHELL (some docker small linux
> distributions do not come with BASH). I have made some modificaitions
> to loops, which allows it to run in both BASH and SHELL.
> 
> If you want to modify the code : here is my version:
> 
> https://github.com/gavalian/language-benchmarks/blob/master/scripts/monitorBanner.sh

HI @gavalian 
i checked your code on both interpreters(Shell and Bash) it's working flawlessly ,

## Updation to Repository:
Adding BannerShell to the current library

## Permissions
Can i add your name in the contributors in ```readme.md``` for ```BannerShell``` addon ?

**Comment by gavalian** [comment]
Hi,

That's nice of you. Sure you can add my name.
